### ISSUE TITLE
Merge all GitHub copies into one?

### ISSUE THREAD

**Issue by larsbrinkhoff** [DavidGriffith/klh10#1]
There are three KLH10 copies at GitHub. I suggest merging them all into one.

I tried to contact KLH but got no reply, so I guess we're on our own.

**Comment by larsbrinkhoff** [comment]
@Rhialto https://github.com/Rhialto/klh10/issues/5
@thequux https://github.com/thequux/klh10/issues/1

**Comment by Rhialto** [comment]
Your commit 6f3815ab36aeea854b011466d2b57f92a8b1a46c looks like something I could take into my version. Is it portable enough though? Would it work with NetBSD's base system version of libusb or does it require a different version? It should probably check in the configure script (some systems might not have it at all).

I think I have the equivalent of the earlier fixes you have.

**Comment by DavidGriffith** [comment]
I wrote it with libusb-1.0 in mind.  Based on a brief perusal of NetBSD's libusb source, I don't think it's compatible.

I don't know if my code is even correct.  I can't get a test program compiled that uses the hooks used to send data to the Panda Display, even with the unmodified Panda distribution.

**Comment by DavidGriffith** [comment]
I got this test program from Jan de Rie who got it from Mark Crispin.  This program is controlling the parallel port Panda Display in this video: https://www.youtube.com/watch?v=g_LcQ5apODg

```
        TITLE HACK
        SEARCH MONSYM

HACK:   SKIPA 4,[^D4]
HACK0:   SOJL 4,TRAILL
        SETZB 1,3
HACK1:  TLNE 1,777777
         JRST HACK0
        MOVE 2,1
        CIRC 2,-^D18
        SKIPN 4
         SKIPA 1,3
          IOR 1,3
        LITES%
         HALT
        HRRZ 2,1
        MOVEI 1,30
        DISMS%
        MOVE 1,2
        AOJA 1,HACK1

TRAILL: SETZ 1,
TRALL0: LITES%
         HALT
        MOVE 2,1
        MOVEI 1,30
        DISMS%
        JUMPL 2,TRAILR
        LSHC 1,^D37
        AOJA 1,TRALL0

TRAILR: MOVSI 1,400000
TRALR0: LITES%
         HALT
        MOVE 2,1
        MOVEI 1,30
        DISMS%
        MOVE 1,2
        TRNE 1,1
         JRST HACK
        ASH 1,-1
        JRST TRALR0

        END HACK
```

**Comment by DavidGriffith** [comment]
On the subject of merging the repos, I'll defer to either of you running the prime repo.

**Comment by Rhialto** [comment]
He definitely knows more about PDP10s than I do!

**Comment by DavidGriffith** [comment]
@larsbrinkhoff, it looks like you've been nominated.

**Comment by larsbrinkhoff** [comment]
Thanks, but to me it seems @Rhialto has done the most work updating KLH10.  My suggestion would be to keep it there, or move it do the PDP-10 organization.

**Comment by Rhialto** [comment]
It seems I can easily add you two as collaborators, to give you commit access. Or I could move it to the PDP-10 organisation. Not sure if that gives any further advantages.

**Comment by larsbrinkhoff** [comment]
I don't think it matters much where it is.  Having it in an organization may make it look more like a community effort, rather than personal.

Hey, the KLH10 user name was free!  I made it a new organization.  Do you want to use that?

**Comment by Rhialto** [comment]
Sure, sounds good.

**Comment by larsbrinkhoff** [comment]
Great, your're both invited to join KLH10.

@Rhialto Whenever you're ready, you can transfer ownership of your repository to the organization.

**Comment by Rhialto** [comment]
Done from my side!

**Comment by larsbrinkhoff** [comment]
Cool!

**Comment by DavidGriffith** [comment]
I thought it would be better to put klh10 under the pdp-10 group since it already exists and has stuff on it.

**Comment by larsbrinkhoff** [comment]
It doesn't matter much to me.  I just happened to see that the KLH10 user name wasn't taken, so I couldn't resist grabbing it.

**Comment by larsbrinkhoff** [comment]
I suppose there may be an advantage to collecting as much 10 stuff as possible in the PDP-10 group.

**Comment by DavidGriffith** [comment]
Soo...  can we do it that way?

**Comment by larsbrinkhoff** [comment]
I'll let @Rhialto have the final say.  Would **PDP-10/klh10** be ok with you?

**Comment by Rhialto** [comment]
Yes, that is also fine with me.

**Comment by larsbrinkhoff** [comment]
Ok, I did the transfer.  I'll check that you both have write access.

**Comment by larsbrinkhoff** [comment]
I have now been in touch with Ken Harrenstien, and he as expressed interest in a GitHub repository.

**Comment by DavidGriffith** [comment]
What are Ken's feelings on how we should proceed?

**Comment by larsbrinkhoff** [comment]
I don't know yet, but I'll let you know!  If Ken doesn't first.

**Comment by DavidGriffith** [comment]
@larsbrinkhoff, do you have anything new to report on Ken's feelings on klh10 and Github?  I'd like to get the differences in my klh10 repo reconciled with the now "official" repo at https://github.com/PDP-10/klh10.

**Comment by larsbrinkhoff** [comment]
No, nothing new.  I haven't heard from Ken in months.

**Comment by ghost** [comment]
From an evolutionary standpoint diversity is a big win. It's not too bad for software development either.
["Let It Go Where It Wants To Go"](https://www.google.com/search?q="let+it+go+where+it+wants+to+go") is sound advice.
_The Cathedral and the Bazaar_ points this out too.

**Comment by DavidGriffith** [comment]
It looks like the new effort is going along quite nicely.  I'll just keep this repo here until the USB Panda Display stuff is worked out.

**Comment by larsbrinkhoff** [comment]
Thanks!  I think this can be closed now.
